[package]
name = "cvitek-phy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
bit_field = "0.10.2"
volatile = "0.3"
smoltcp = { version = "0.10.0", features = ["alloc", "log","medium-ethernet","proto-ipv4","socket-raw", "socket-icmp", "socket-udp", "socket-tcp", "socket-dns"], default-features = false}

[features]
default = []