[package]
name = "cvitek_phy_test"
version = "0.1.0"
edition = "2021"

[features]

default = ["libax/default"]

[dependencies]
libax = { path = "../../../ulib/libax", default-features = false, features = ["paging","multitask","cvitekphy","irq"]}